sudo: false
language: node_js
node_js:
  - "node"
  - "7.6.0"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"

install:
  # The default "npm ci" fails with NPM v6.
  - npm install

notifications:
  email: ["andri@dot.ee"]
